import { resolve } from 'node:path'
import { execSync } from 'node:child_process'
import type { DatabaseAdapter } from '../adapters/DatabaseAdapter.js'
import type { DrizzleAdapter } from '../adapters/DrizzleAdapter.js'
import type { PrismaAdapter } from '../adapters/PrismaAdapter.js'
import type { TypeORMAdapter } from '../adapters/TypeORMAdapter.js'

export interface MigratorOptions {
  /**
   * Folder containing migration files.
   * - Drizzle: folder of SQL migration files generated by drizzle-kit
   * - Prisma:  not used (prisma migrate uses its own folder)
   * - TypeORM: folder of migration class files
   * - None:    not applicable
   */
  migrationsFolder?: string
}

/**
 * Migrator — runs database migrations for whichever ORM is in use.
 *
 * Pearl's CLI (`pearl migrate`) delegates to this class.
 * You can also call it manually in your DatabaseServiceProvider boot()
 * if you want migrations to run on every app start.
 *
 * @example
 *   const migrator = new Migrator(adapter, { migrationsFolder: './database/migrations' })
 *   await migrator.run()
 */
export class Migrator {
    constructor(
        private readonly adapter: DatabaseAdapter,
        private readonly options: MigratorOptions = {},
    ) {}

    async run(): Promise<void> {
        // Detect adapter type by duck-typing — avoids circular imports
        const adapterName = this.adapter.constructor.name

        switch (adapterName) {
            case 'DrizzleAdapter':  return this._runDrizzle()
            case 'PrismaAdapter':   return this._runPrisma()
            case 'TypeORMAdapter':  return this._runTypeORM()
            case 'NoneAdapter':
                throw new Error('[Pearl] Migrator: cannot run migrations with NoneAdapter — no ORM is configured.')
            default:
                throw new Error(`[Pearl] Migrator: unknown adapter "${adapterName}".`)
        }
    }

    // ─── Drizzle ────────────────────────────────────────────────────────────────

    private async _runDrizzle(): Promise<void> {
        const folder = this._requireFolder('Drizzle')
        const drizzle = this.adapter as DrizzleAdapter
        const db = drizzle.db

        // Detect driver from the db instance — Drizzle sets a dialect symbol
        // Fall back to trying all three migrators in sequence
        const resolved = resolve(folder)

        try {
            const { migrate } = await import('drizzle-orm/node-postgres/migrator')
            await migrate(db, { migrationsFolder: resolved })
            return
        } catch {}

        try {
            const { migrate } = await import('drizzle-orm/mysql2/migrator')
            await migrate(db, { migrationsFolder: resolved })
            return
        } catch {}

        const { migrate } = await import('drizzle-orm/better-sqlite3/migrator')
        await migrate(db, { migrationsFolder: resolved })
    }

    // ─── Prisma ─────────────────────────────────────────────────────────────────

    private _runPrisma(): void {
        // Prisma migrations are always run via the prisma CLI — we shell out here
        // so `pearl migrate` still works as a single command regardless of ORM.
        console.log('[Pearl] Running: prisma migrate deploy')
        execSync('npx prisma migrate deploy', { stdio: 'inherit' })
    }

    // ─── TypeORM ────────────────────────────────────────────────────────────────

    private async _runTypeORM(): Promise<void> {
        const typeorm = this.adapter as TypeORMAdapter
        const ds = typeorm.dataSource

        if (!ds.isInitialized) {
            throw new Error('[Pearl] TypeORMAdapter: DataSource must be initialized before running migrations.')
        }

        console.log('[Pearl] Running TypeORM migrations...')
        const ran = await ds.runMigrations({ transaction: 'all' })
        console.log(`[Pearl] ${ran.length} migration(s) applied.`)
    }

    // ─── Helpers ────────────────────────────────────────────────────────────────

    private _requireFolder(orm: string): string {
        if (!this.options.migrationsFolder) {
            throw new Error(
                `[Pearl] Migrator: migrationsFolder is required for ${orm}. ` +
                `Set it in your DatabaseServiceProvider.`,
            )
        }
        return this.options.migrationsFolder
    }
}

export type { MigratorOptions as MigratorConfig }